redhat-marketplace/redhat-marketplace-operator

Makefile, docs/getting-started.md, scripts/operator_sdk_sa_kubeconfig.sh, scripts/scorecard_with_kind.sh
Separated setup-operator-sdk-run and operator-sdk-run. Then we can re-run `make operator-sdk-run` to catch the latest code changes without re-creating ns, sa, role,...
=> add operator-sdk commands to Makefile

Makefile, deploy/role.yaml, deploy/service_account.yaml, pkg/controller/razeedeployment/razeedeployment_controller.go
[Addresses razeedeployment continuously queue for reconcile](https://github.ibm.com/symposium/track-and-plan/issues/7495)
Previously RazeeDeployment would reconcile when any secret (regardless of namespace / affiliation) was deleted. Added to ```predicate.Funcs``` to only reconcile when appropriate secrets are deleted. 
**How to Test**
* `make setup-operator-sdk-run operator-sdk-run`
* Create then delete the following resource:
```
apiVersion: v1
kind: Namespace
metadata:
name: my-etcd-1
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
name: operatorgroup
namespace: my-etcd-1
spec:
targetNamespaces:
- my-etcd-1
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: etcd
namespace: my-etcd-1
spec:
channel: singlenamespace-alpha …
```
=> fix: RazeeDeployment no longer reconciles when any secret is deleted

build/Dockerfile
Our images are being flagged for a high vulnerability. This will fix it and make sure updates are made on top of the ubi minimal image we use as a base.
=> chore: add update to dockerfile

Makefile, cmd/manager/main.go, cmd/manager/wire_gen.go, deploy/chart/values.yaml, pkg/controller/add_clusterserviceversion.go, pkg/controller/clusterserviceversion/clusterserviceversion_controller.go, pkg/controller/clusterserviceversion/clusterserviceversion_controller_test.go, pkg/controller/node/node_controller.go
Issue: https://github.ibm.com/symposium/track-and-plan/issues/7517
What changed:
Added a controller for CSV for adding label ["razee/watch-resource":"lite"] if subscription has rhm operator label
Updated the roles for ClusterServiceVersion resources
Not attaching razee watch label to the copied CSVs for allNamespace subscriptions
=> Feature/add CSV controller

deploy/chart/values.yaml, pkg/controller/marketplaceconfig/marketplaceconfig_controller.go, pkg/controller/marketplaceconfig/marketplaceconfig_controller_test.go, pkg/utils/env.go, pkg/utils/k8s.go
https://github.ibm.com/symposium/track-and-plan/issues/8030
What changed: 
I moved the code to create a catalog source to a function and reused it for both IBM catalog source and Opencloud catalog source. The logic to create a catalog source was not changed.
=> feat(opencloudCatSrc): added opencloud catalog source

pkg/controller/meterbase/meterbase_controller.go
Quick bug-fix. Previously when deleting resources (meterbase, prometheus, rhm-metric-state), the service `rhm-metric-state-service`, wasn't being deleted. Now it should.
=> fix: delete rhm-metric-state-service on uninstall

pkg/reporter/builder.go, pkg/reporter/builder_test.go, pkg/reporter/reporter.go
This PR will add a few fields to the meter report ID generation to make it more unique. Currently reruns will not happen if the meter report was updated.
=> fix(reporter): more unique meter ID generation

build/base.Dockerfile
The default ARCH is amd64.
The image can be built using below
docker build --build-arg ARCH=ppc64le -t quay.io/rh-marketplace/golang-base:1.15 -f build/base.Dockerfile .
on ppc64le
The ARCH of the built image
docker inspect quay.io/rh-marketplace/golang-base:1.15 | grep -i arch
"ARCH=ppc64le"
"architecture": "ppc64le",
"ARCH=ppc64le"
"architecture": "ppc64le",
"Architecture": "ppc64le",
and the environment variable
docker run --rm=true -it quay.io/rh-marketplace/golang-base:1.15 bash
[root@1637d03cbdd6 /]# echo $ARCH
ppc64le
show up correctly.
=> support native build for base-base image on non amd64 architectures (using build-arg)

pkg/reporter/builder.go, pkg/reporter/builder_test.go, pkg/reporter/reporter.go
This PR adds an alternative uploader and different file format to support direct file uploads to sandbox.
To test it run
```sh
go run ./cmd/reporter/main.go report --name <REPORT_NAME> --namespace <REPORT_NAMESPACE> --local --uploadTarget noop
```
=> feature: adding support json payload for rhm backend

.travis.yml
Updated .travis.yml file to build and generate the docker images for Power and push them to quay.io. Also executing unit tests on power.
Travis job details:
https://travis-ci.org/github/kandarpamalipeddi/redhat-marketplace-operator/builds/745401226
Pushed images can be found at :
https://quay.io/repository/kandarpamalipeddi/redhat-marketplace-authcheck
https://quay.io/repository/kandarpamalipeddi/redhat-marketplace-metric-state
https://quay.io/repository/kandarpamalipeddi/redhat-marketplace-operator
https://quay.io/repository/kandarpamalipeddi/redhat-marketplace-reporter
Quay credentials are being used as following environment variable in Travis job (.travis.yml file):
Quay user name : $ROBOT_USER_NAME
Passphrase : $ROBOT_PASS_PHRASE
Please review the changes and let me know comments.
=> Generating docker images for Power using travis.yml, pushing into quay

.travis.yml, Makefile
Updated .travis.yml file to build container images for IBM Z (s390x) in Travis CI and push to quay.io. Also executing unit tests on s390x. Realized that existing power scripts were out of sync with the latest Dockerfiles.  Actualized those by passing required docker build arguments. 
Travis job details:
https://travis-ci.com/github/aosadchyy/redhat-marketplace-operator/jobs/462660422
Pushed images can be found at :
https://quay.io/repository/aosadchyy/redhat-marketplace-authcheck
https://quay.io/repository/aosadchyy/redhat-marketplace-metric-state
https://quay.io/repository/aosadchyy/redhat-marketplace-operator
https://quay.io/repository/aosadchyy/redhat-marketplace-reporter
Quay credentials must be specified in Travis CI environment variables. They are  being used as following in Travis …
=> Build container images for IBM Z (s390x) in Travis CI and push to quay.io

reporter/v2/pkg/reporter/query.go
Edge case
- multiple rhm-metric-state pods end up running 
- duplicate time series are produced with a different pod/instance tag
Results in reporter/prometheus error
- found duplicate series for the match group
- many-to-many matching not allowed: matching labels must be unique on one side
The new query string should still remove the extraneous labels, and compact the result into a set of non-duplicate active meter definitions
=> prevent duplicate series for the match group

v2/controllers/marketplace/meterbase_controller.go, v2/controllers/marketplace/razeedeployment_controller.go, v2/pkg/manifests/factory.go, v2/pkg/utils/reconcileutils/finalizerAction.go
Modify Factory Set(Owner/Controller)Reference to (owner, obj) to be consistent with controllerutil
- Update uses of Set(Owner/Controller)Reference
Do not remove MarketplaceConfig finalizer until child objects are removed (by correcting finalizerAction)
Do not set an OwnerReference on RemoteResourceS3Deployment
- If a foreground deletion is called (kubectl delete --cascade='foreground'), the RRS3 Deployment will be deleted before the finalizer can cleanup child/parent rrs3
=> correct finalizer

v2/controllers/marketplace/marketplaceconfig_controller.go, v2/pkg/utils/env.go
work for issue: [https://github.ibm.com/symposium/track-and-plan/issues/15303](url)
Checks for CLUSTER_DISPLAY_NAME field on rhm pull secret, if under 256 chars, updates marketplace config ClusterName.
=> use CLUSTER_DISPLAY_NAME from rhm-pull-secret to set ClusterName on marketplace config

v2/assets/metric-state/kube-state-metrics-service.yaml, v2/assets/metric-state/meterdefinition.yaml, v2/assets/prometheus/meterdefinition.yaml, v2/assets/prometheus/service-monitor.yaml, v2/assets/prometheus/user-workload-monitoring-meterdefinition.yaml, v2/assets/prometheus/user-workload-monitoring-service-monitor.yaml, v2/assets/reporter/meterdefinition.yaml, v2/assets/reporter/user-workload-monitoring-job.yaml, v2/controllers/marketplace/meterbase_controller.go, v2/controllers/marketplace/meterdefinition_controller.go, v2/controllers/marketplace/meterreport_controller.go, v2/pkg/manifests/factory.go, v2/pkg/prometheus/query.go, v2/pkg/prometheus/thanos_api.go, v2/pkg/prometheus/thanos_client.go, v2/pkg/utils/env.go
Add kube-state-metrics-service such that the MeterDefinition for rhm-meter-report-job-failed has a service match. Alternatively, the MeterDefinition could be created in the openshift-monitoring namespace.
Meterdefinitions to track uptime: rhm-metric-state-uptime, rhm-prometheus-meterbase-uptime, prometheus-user-workload-uptime
Servicemonitors to support tracking uptime: rhm-prometheus-meterbase, prometheus-user-workload
user-workload-monitoring-job.yaml is the Job run when using UWM, as the ca-bundle and audience is different
meterbase_controller
Add additional install/uninstall of servicemonitor, meterdefinition for self-monitoring
Use Thanos Querier service for UWM Query/QueryRange, which results in the merged cluster(kube-state) & user-workload(servicemonitors) metrics
Continue to …
=> metering uptime and uwm fixes

v2/pkg/config/config.go, v2/pkg/config/config_test.go, v2/pkg/manifests/factory.go, v2/pkg/manifests/factory_test.go
- Adds a env flag called `CONFIG` where you can set container resources
- Adds function to factory to match containers by name and override container resources based on the `CONFIG` configuration.
For example, setting a config env flag on the subscription override the limits for "system" and "system2" container names.
```
CONFIG: {"resources":{"containers":{"system":{"limits":{"cpu":"500m"}},"system2":{"limits":{"cpu":"1"}}}}}
```
=> bugfix: Configurable Resources

reporter/v2/cmd/reporter/reconciler/reconcile.go, reporter/v2/cmd/reporter/report/report.go, reporter/v2/pkg/reporter/reconcile_task.go, reporter/v2/pkg/reporter/task.go, reporter/v2/pkg/reporter/uploader.go, reporter/v2/pkg/reporter/wire.go, reporter/v2/pkg/reporter/wire_gen.go, v2/assets/reporter/cronjob.yaml, v2/config/rbac/classic/role.yaml
create broadcaster at top level that can optionally be passed to Task functions
task records ReportJobError type to events on the Job object before returning
the Event will send the ReportJobError.ErrorMessage to the Event (not the stack)
Is there anything more specific you want in the Event message?
ReconcileTask.Run was accumulating errors without returning them
Which I modified for CanRunUploadTask, but not range meterReportsToRun
Do we want to do something specific about this?
=> send events for disabled insights

v2/controllers/marketplace/meterbase_controller.go
- Send an event for DefaultClassNotFound for userWorkloadMonitoring, just as we do with rhm-prometheus setup.
- Send the event, but do not stop reconciliation, as user could have setup a storageclass manually for UWM
=> uwm event for DefaultStorageClassNotFound

base/base.Dockerfile, v2/apis/marketplace/v1alpha1/zz_generated.deepcopy.go, v2/assets/metric-state/secret.yaml, v2/assets/razee/rrs3-controller-deployment.yaml, v2/assets/razee/watch-keeper-deployment.yaml, v2/config/crd/bases/marketplace.redhat.com_marketplaceconfigs.yaml, v2/config/crd/bases/marketplace.redhat.com_meterbases.yaml, v2/config/crd/bases/marketplace.redhat.com_meterdefinitions.yaml, v2/config/crd/bases/marketplace.redhat.com_meterreports.yaml, v2/config/crd/bases/marketplace.redhat.com_razeedeployments.yaml, v2/config/crd/bases/marketplace.redhat.com_remoteresources3s.yaml, v2/config/rbac/role.yaml, v2/controllers/marketplace/meterbase_controller.go, v2/controllers/marketplace/meterreport_controller.go, v2/pkg/config/config.go, v2/pkg/manifests/factory.go, v2/pkg/prometheus/promcfg.go, v2/pkg/prometheus/prometheus_api.go, v2/pkg/prometheus/prometheus_client.go, v2/pkg/prometheus/thanos_api.go, v2/pkg/prometheus/thanos_client.go, v2/pkg/utils/predicates/predicates.go, v2/pkg/utils/predicates/predicates_suite_test.go, v2/pkg/utils/predicates/predicates_test.go, v2/tests/metadata/golden/role.yaml
Secrets and service monitors started to have issues back when the UWM feature was first created. So the project transitioned from using a static one, to creating one based on the current token, to just trying to use the same secret on the operator pod. This last method broke with 4.8. This PR looks to address that.
This solution generates a token but makes sure to generate a uniquely named one, and the secret is tied to the pod of the operator. So if the pod is deleted, this secret will be cleaned up and on reinstall a new one. This prevents an issue that can occur when the secret is no longer valid.
What it does:
- Generate a new secret in the openshift-redhat-marketplace ns
- If the secret is deleted, it will get recreate automatically.
- If the pod is deleted, it'll delete the secret. …
=> bugfix: fixing 4.8 secret issues

v2/Makefile, v2/apis/marketplace/v1alpha1/remoteresources3_types.go, v2/assets/prometheus-operator/deployment-v4.5.yaml, v2/assets/prometheus-operator/deployment-v4.6.yaml, v2/assets/razee/rrs3-controller-deployment.yaml, v2/config/crd/bases/marketplace.redhat.com_marketplaceconfigs.yaml, v2/config/crd/bases/marketplace.redhat.com_meterbases.yaml, v2/config/crd/bases/marketplace.redhat.com_meterdefinitions.yaml, v2/config/crd/bases/marketplace.redhat.com_meterreports.yaml, v2/config/crd/bases/marketplace.redhat.com_razeedeployments.yaml, v2/config/crd/bases/marketplace.redhat.com_remoteresources3s.yaml, v2/config/crd/patches/remotes3_disable_preserve_unknown_fields.yaml, v2/config/rbac/classic/role.yaml, v2/controllers/marketplace/razeedeployment_controller.go, v2/pkg/manifests/factory.go, v2/pkg/utils/envvar/envvar_test.go
Changes
- Add unknown-fields attribute to RRS3 spec (required for v1 to work)
- Patches RRS3 deployment asset yaml to fix pathing issues with startup
- Patches razeedeployment controller to get past equality checks on secret data (infinite loop, yay)
- Removes HTTPS_PROXY being set to "" on RRS3 and watchkeeper.
- Resets permissions to 2.3.4
- Bumps limits on Prometheus Operator to prevent OOM
=> bugfix: fix rrs3 reconcilation

v2/Makefile, v2/hack/certify/certify.sh, v2/hack/certify/sub.yaml
To pass certification checks
- annotations.yaml needs
- openshift.versions
- CHANNELS, DEFAULT_CHANNELS with default; must be set to generate their required associated annotations
- remove the operator service account yaml, this should be created by OLM & fails a cert check
- didn't seem to be a great way to remove it via a kustomize option; make bundle vs. make install needing the sa
=> WIP Feature/cert pipeline

v2/controllers/marketplace/razeedeployment_controller.go
- Use mergo to merge/enforce spec on Deployment when using CreateOrUpdate
- mergo.WithOverride replaces slices, which could otherwise cause problems for things like volume list on upgrade
=> mergo for rrs3 CreateOrUpdate

v2/pkg/config/config.go
Do not override RelatedImages in a disconnected environment
=> disconnected no relatedimage override

metering/v2/pkg/dictionary/cache.go, tests/v2/e2e/userworkloadmonitoring-test/01-uwm-config.yaml, tests/v2/e2e/userworkloadmonitoring-test/21-uwm-config.yaml, tests/v2/e2e/userworkloadmonitoring-test/41-uwm-config.yaml, utils.Makefile, v2/controllers/marketplace/meterdefinition_controller.go, v2/hack/certify/certify.sh, v2/hack/certify/sub.yaml
remove debug statement in cache.go
update e2e uwm test config to minimum required values
add a set UNAME_S to utils.Makefile
add --wildcards flag to tar extract for buf for linux
remove use of matches in prometheusAPI.MeterDefLabelValues due to error
unsure why error occurs, could be a bug, could be due to thanos target, and it doesn't support matches?
update certification script with submit check, required secret creation, and create namespace for webhook/finalizer workaround
=> various fixes

reporter/v2/pkg/reporter/report_task.go, reporter/v2/pkg/reporter/reporter.go, reporter/v2/pkg/reporter/wire_gen.go, reporter/v2/pkg/uploaders/localfile.go, v2/apis/marketplace/common/prometheus.go, v2/pkg/prometheus/prometheus_client.go, v2/tools/connect/pkg/client.go
Local execution had a lot of issues with variables being used when not necessary. While running a report now this tool will work if using local values:
```
go run cmd/reporter/main.go report --name meter-report-2021-12-13 --namespace openshift-redhat-marketplace --local --uploadTargets=local-path --localFilePath=`pwd`
```
will now work as expected.
Note: you have to port-forward 9090 from the prometheus you're querying
=> fix: fix local execution of report tool

v2/controllers/marketplace/clusterserviceversion_controller.go, v2/controllers/marketplace/clusterserviceversion_jsonannotation_test.go
For: https://github.ibm.com/symposium/track-and-plan/issues/22915
Our predicates were looking for the csv namespace to match the namespace set by olm on `olm.operatorNamespace` upon creation of the csv
```
func csvFilter(metaNew metav1.Object) int {
ann := metaNew.GetAnnotations()
//annotation values
ignoreVal, hasIgnoreTag := ann[ignoreTag]
_, hasCopiedFrom := ann[olmCopiedFromTag]
_, hasMeterDefinition := ann[utils.CSV_METERDEFINITION_ANNOTATION]
sameNamespace := ann[olmNamespace] == metaNew.GetNamespace()
switch {
// has meterdef && is not an all namespace install
case hasMeterDefinition && !hasCopiedFrom && sameNamespace:
return 1
// does not have a meterdef and
case !hasMeterDefinition && (!hasIgnoreTag || ignoreVal != ignoreTagValue):
return 2
default:
}
return 0
}
```
The problem …
=> requeue if olm.operatorNamespace isn't set yet

v2/assets/prometheus/service.yaml, v2/config/rbac/classic/role.yaml, v2/config/rbac/role.yaml, v2/controllers/marketplace/meterbase_controller.go
ose-prometheus:v4.10 used for rhm-prometheus no longer adds the label `app: prometheus` to prometheus pods
this was causing calls to the prometheus service endpoint to fail
do not use it as a service label selector
v4.6-v4.10 retains use of the `prometheus: ` label, continue to use that as the selector
---
add required rbac for rhm-prometheus kubelet servicemonitor
=> fix: v4.9-v4.10 rhm-prometheus service

v2/assets/dataservice/statefulset.yaml
For: https://github.ibm.com/symposium/track-and-plan/issues/24058
- Adds resource limit to `assets/dataservice/statefulset.yaml`
=> added cpu and memory limits on data-service

v2/controllers/marketplace/clusterregistration_controller.go
- ensure that accountID is set on MarketplaceConfig when ibm-entitlement-key is used
- accountID is needed in the MarketplaceConfig spec, as consumed by marketplaceconfig_controller/marketplace_client to check registration status & unregister
=> fix: set marketplaceconfig accountid for iek

v2/pkg/marketplace/marketplace_client.go
The response body of a PATCH call to RegistrationEndpoint is empty
- Do not try to parse the response body as json via getRegistrations, it just throws an error
- A 200 OK indicates we are successful
- Just return an UNREGISTERED for RegistrationStatusOutput if we got a 200 OK
- get rid of a debug print
---
Could be extra diligent, but this does hold up our finalizer
- Check RegistrationEndpoint registrationStatus for TO_BE_UNREGISTERED status after the RegistrationEndpoint PATCH call
- retryablehttp a few times if we failed
=> fix unregister reponse handling

authchecker/v2/pkg/authchecker/authchecker.go, authchecker/v2/pkg/authchecker/authchecker_test.go
Fix for bug [24892](https://github.ibm.com/symposium/track-and-plan/issues/24892)
Sigfaults:
```
2022-05-16T22:39:31.659Z  INFO   controller-runtime.healthz  healthz check failed  {"statuses": [{}]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98b5f9]
goroutine 7 [running]:
github.com/redhat-marketplace/redhat-marketplace-operator/authchecker/v2/pkg/authchecker.(*AuthChecker).CheckToken(0xc0002d8100, {0xc22858, 0xc000290700})
/src/authchecker/v2/pkg/authchecker/authchecker.go:98 +0x59
github.com/redhat-marketplace/redhat-marketplace-operator/authchecker/v2/pkg/authchecker.(*AuthChecker).Start.func1()
/src/authchecker/v2/pkg/authchecker/authchecker.go:80 +0xd9
created by …
```
=> bugfix: fix nil pointer

v2/config/rbac/role.yaml, v2/controllers/marketplace/meterbase_controller.go
Fix for [24843](https://github.ibm.com/symposium/track-and-plan/issues/24843).
Adding nonResourceURLS /metrics for the rhm-metric-state service monitor token to work.
=> bugfix: no data due to permissions

v2/controllers/marketplace/clusterserviceversion_controller.go, v2/controllers/marketplace/clusterserviceversion_controller_test.go
This is for 24809 opened against RC 2.7.1
- Do not reconcile CSV deletes
- We do not set finalizers on CSVs
- Remove MeterDefinition delete logic, they are removed via OwnerRef
- Fix the csvFilter predicate
- olmCopiedFromTag  / olm.copiedFrom is a Label not an Annotation, so the predicate was not filtering as intended
- We were still reconciling for CSV copies, though reconcileMeterDefAnnotation() would catch these as copies and return anyways
There may still be an `Error Not Found` due to timing, as OLM fires a Status update against the primary CSV as an operator is being deleted. We can't ignore Status update events, as we consume Status in our reconcile.
=> fix: csv filter

v2/config/rbac/role.yaml, v2/controllers/marketplace/clusterregistration_controller.go, v2/controllers/marketplace/marketplaceconfig_controller.go, v2/controllers/marketplace/meterbase_controller.go, v2/controllers/marketplace/razeedeployment_controller.go, v2/controllers/marketplace/razeedeployment_controller_test.go, v2/pkg/utils/env.go
Problem in issue 24954
```
oc delete MarketplaceConfig marketplaceconfig -n openshift-redhat-marketplace
oc delete subscription  redhat-marketplace-operator -n openshift-redhat-marketplace
oc get csv -n openshift-redhat-marketplace --no-headers | awk '/redhat-marketplace-operator/{print $1}'  | xargs oc delete -n openshift-redhat-marketplace csv
```
The lack of ownerref/blockOwnerDeletion on MarketplaceConfig allowed the Controller to be deleted before the finalizer was processed
- via the CSV delete - deletes the Controller Deployment
With this change, this should not happen, and following the deletion commands, we should see no resources stuck with finalizers, and should thus be able to also cleanly delete the namespace
```
oc get …
```
=> Fix finalizers & ownerRefs

airgap/v2/pkg/database/filestore.go, reporter/v2/pkg/reporter/upload_task.go, reporter/v2/pkg/uploaders/marketplace.go, reporter/v2/pkg/uploaders/marketplace_test.go
**Tickets:**
https://zenhub.ibm.com/workspaces/symposium-workflow-5c49e21b79c5ae72931da0d6/issues/symposium/track-and-plan/25629
https://zenhub.ibm.com/workspaces/symposium-workflow-5c49e21b79c5ae72931da0d6/issues/symposium/track-and-plan/25827
**Changes:**
- Updated report uploader logic to solely depend on the status of the upload POST call
- Removed `statusRequest` function and other relevant components
- Updated/fixed unit tests
- Discussed with Mari, and removed conflict checks and retry checks from `checkError` logic 
- Updated upload task to delete the file from DataService only when the backend upload is successful.
=> Update reporter flow

reporter/v2/cmd/reporter/reconciler/reconcile.go, reporter/v2/cmd/reporter/report/report.go, reporter/v2/pkg/reporter/reconcile_task.go, reporter/v2/pkg/reporter/reconcile_task_test.go
- We run the cronjob hourly
- Set the retry limit to 24 to allow 1 full day of retries
=> fix: default to 24 retries

v2/controllers/marketplace/meterbase_controller.go, v2/controllers/marketplace/razeedeployment_controller.go, v2/pkg/marketplace/marketplace_client.go
- handle err in marketplace client, if request fails, it leads to an NPE
- add a remove finalizer check for meterbase and razeedeployment
- we no longer use the finalizer for cleanup of these objects, and use the ownerRef to have kube GC them
- in an upgrade situation, if the finalizer was set by an older version, it would cause cleanup to fail with stuck finalizers (ex; upgrade 2.7.0 -> 2.7.1 -> uninstall)
=> fix: ownerref and npe

v2/controllers/marketplace/meterbase_controller.go, v2/pkg/utils/env.go
**Ticket:**
https://zenhub.ibm.com/workspaces/symposium-workflow-5c49e21b79c5ae72931da0d6/issues/symposium/track-and-plan/23520
**Changes:**
- Updated meterbase_controller to include a watch on System MeterDefinitions, and it reconciles when they are updated or deleted.
=> fix: reconcile system meterdefs

airgap/v2/Dockerfile, authchecker/v2/Dockerfile, base/Makefile, metering/v2/Dockerfile, reporter/v2/Dockerfile, utils.Makefile, v2/Dockerfile, v2/Makefile
- move dataservice to 1.17
- use explicit `--mount=` args, buildah/podman does not accept the shortcut
- fix the docker-push for base makefile
- fix the space var for utils.Makefile, it would otherwise leave a trailing comma in the arg which buildah/podman would fail on
- do not use a --push or --load with podman, the args are not available
_works for me_ with 
buildah 1.26.1
podman 4.1.0
rhel 9.0
=> bugfix: buildah/podman support, dataservice 1.17

base/dataservice.Dockerfile
also build the grpc-health-probe in the dqlite-lib-builder image on our current version of golang, in case we need to ship a CVE fix
we can choose which one we copy later in the airgap Dockerfile
=> chore: build grpc-health-probe on current golang version

airgap/v2/Dockerfile, base/dataservice.Dockerfile
with untimely releases of grpc-health-probe release binary for CVEs, instead build/install using our (latest) version of golang
=> fix: use self-built grpc-health-probe

airgap/v2/buf.lock, authchecker/v2/Dockerfile, metering/v2/go.mod, metering/v2/go.sum, metering/v2/pkg/engine/runnables.go, metering/v2/pkg/engine/suite_test.go, v2/config/manifests/bases/redhat-marketplace-operator.clusterserviceversion.yaml, v2/controllers/marketplace/meterbase_controller.go, v2/pkg/utils/env.go
- remove go-health due to unresolvable deps. use of was not fully implemented anyways.
- Allow an upgrade from v2.x -> v2.9.0 to continue using RHM Prom (until vnext)
- Disallow a new v2.9.0 install from creating RHM Prom, must use UWM
- Operator: Log a deprecation warning message if RHM Prom is being used (upgrade users), and that they should transition
- Operator: Generate an Event warning message if RHM Prom is being used (upgrade users), and that they should transition
=> feat: deprecate rhm prometheus

v2/apis/marketplace/v1alpha1/api_suite_test.go, v2/apis/marketplace/v1beta1/webhook_suite_test.go, v2/controllers/marketplace/suite_test.go, v2/pkg/catalog/catalog_suite_test.go, v2/pkg/config/config_suite_test.go
Description:
This PR removes printer package import which is removed in sigs.k8s.io/controller-runtime v0.14.0.
We haven't upgraded the package version in go.mod because when we update the version and run `go mod tidy`, it also upgrades k8s.io/api version.
=> Removed printer package import

deployer/v2/Makefile, v2/Makefile
Update to supported range
https://access.redhat.com/support/policy/updates/openshift
=> OpenShift v4.9-v4.12 as supported versions

deployer/v2/config/rbac/role.yaml, deployer/v2/controllers/marketplace/deployment_controller.go, deployer/v2/main.go, v2/assets/metrics-operator/metrics-ca-bundle-configmap.yaml, v2/assets/metrics-operator/metrics-service-monitor.yaml, v2/assets/metrics-operator/metrics-service.yaml, v2/assets/metrics-operator/servicemonitor-metrics-reader-secret.yaml, v2/assets/redhat-marketplace-operator/metrics-ca-bundle-configmap.yaml, v2/assets/redhat-marketplace-operator/metrics-service-monitor.yaml, v2/assets/redhat-marketplace-operator/metrics-service.yaml, v2/assets/redhat-marketplace-operator/servicemonitor-metrics-reader-secret.yaml, v2/config/rbac/role.yaml, v2/controllers/marketplace/deployment_controller.go, v2/main.go, v2/pkg/manifests/factory.go, v2/pkg/utils/env.go
create controller for each operator that specifically reconciles the loose bundle manifests 
problem: typically OLM will create the 4 bundle loose resources: secret, servicemonitor, service, configmap which enable protected /metrics endpoint. The Deployment specifically relies on the configmap volume to start. The secret can be prematurely destroyed if OLM creates the ServiceAccount before the Secret, as the Secret reconciler will delete an annotated secret if the serviceaccount does not exist (yet). The loose resources are not reconciled by OLM if they are modified/deleted.
=> deployment controller

datareporter/v2/api/v1alpha1/datareporterconfig_types.go, datareporter/v2/config/manifests/bases/ibm-data-reporter-operator.clusterserviceversion.yaml, datareporter/v2/pkg/events/event_processor.go, datareporter/v2/pkg/events/event_reporter.go, reporter/v2/pkg/reporter/uploader.go
- NewDataService makes an intial grpc connection to the server
- move the NewDataService into the scope of Start() instead of NewEventReporter
- set a status on datareporterconfig if the initial connection fails, typically if dataservice is not available yet
- can scale down deploy/ibm-metrics-operator-controller-manager sts/rhm-data-service to test
- provideDataService will loop until the connection is established and a DataService can be returned, the timeout/retry is 60 seconds via the underlying context
=> retry initial conn

datareporter/v2/controllers/datareporterconfig_controller.go, v2/apis/marketplace/v1alpha1/marketplaceconfig_types.go, v2/controllers/marketplace/clusterregistration_controller.go, v2/controllers/marketplace/marketplaceconfig_controller.go, v2/controllers/marketplace/marketplaceconfig_controller_test.go
https://github.ibm.com/symposium/track-and-plan/issues/28053
Scenarios to verify:
- fresh install, user has to add manually license.accept in MarketplaceConfig to register cluster
- upgrade, license.accept should be added automatically on update
=> added check for license

README.md, datareporter/v2/Makefile, datareporter/v2/config/default/manager_auth_proxy_patch.yaml, deployer/v2/Makefile, deployer/v2/config/default/manager_auth_proxy_patch.yaml, deployer/v2/config/manifests/bases/CSV_description.md, deployer/v2/config/manifests/bases/redhat-marketplace-operator.clusterserviceversion.yaml, utils.Makefile, v2/Makefile, v2/config/default/manager_auth_proxy_patch.yaml, v2/config/manager/kustomization.yaml, v2/config/manager/manager.yaml, v2/config/manifests/bases/CSV_description.md, v2/config/manifests/bases/ibm-metrics-operator.clusterserviceversion.yaml, v2/pkg/config/config.go
- fix links to use _latest_
- publish bundle supporting 4.13
- this does not bring up the modules to the kube 1.26 / ocp 4.13 set
=> feat: support ocp 4.13

datareporter/v2/config/default/manager_auth_proxy_patch.yaml, deployer/v2/config/default/manager_auth_proxy_patch.yaml, metering/v2/test/engine_testcase1/pod.yaml, v2/assets/catalog-server/deployment-config.yaml, v2/assets/dataservice/statefulset.yaml, v2/assets/metric-state/deployment.yaml, v2/assets/prometheus-operator/deployment-v4.6.yaml, v2/assets/prometheus/prometheus-v4.6.yaml, v2/config/default/manager_auth_proxy_patch.yaml
```
oc logs ibm-data-reporter-operator-controller-manager-78b78dc98b-zb5tv -c kube-rbac-proxy
Flag --logtostderr has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
```
---
```
oc logs rhm-metric-state-8f7c7f8f5-49d4v -c kube-rbac-proxy-1
==== Deprecation Warning ======================
Insecure listen address will be removed.
Using --insecure-listen-address won't be possible!
The ability to run kube-rbac-proxy without TLS certificates will be removed.
Not using --tls-cert-file and --tls-private-key-file won't be possible!
For more information, please go to https://github.com/brancz/kube-rbac-proxy/issues/187 …
```
=> remove use of deprecated flags from kube-rbac-proxy

datareporter/v2/config/default/manager_auth_proxy_patch.yaml, deployer/v2/Makefile, deployer/v2/config/default/manager_auth_proxy_patch.yaml, deployer/v2/config/manager/manager.yaml, v2/assets/catalog-server/deployment-config.yaml, v2/assets/dataservice/statefulset.yaml, v2/assets/metric-state/deployment.yaml, v2/assets/razee/remote-resource-s3.yaml, v2/assets/razee/rr-controller-deployment.yaml, v2/assets/razee/watch-keeper-deployment.yaml, v2/assets/razee/watch-keeper.yaml, v2/config/default/manager_auth_proxy_patch.yaml, v2/pkg/config/config.go, v2/pkg/utils/env.go
- Set GOMEMLIMIT env to make go garbage collection aware of the container limit, and prevent OOMKilled
- Set authcheck to 24Mi as needed by fips-detect during startup
- Set kube-rbac-proxy limit to 32Mi, in testing it seemed necessary to prevent OOMKilled from a traffic burst
- Update the razee images, now that the multi-arch is fixed on the manifest
```
skopeo inspect  --raw docker://us.icr.io/armada-master/watch-keeper:0.8.9_5bbfd59
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1728,
"digest": "sha256:c1ac9fcab98dcdf39c9be878386c0e3bc01dea90ad125c67d7f3db0ef9170ca9",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": …
```
=> set gomemlimit, update mem limit, update razee images

base/dataservice.Dockerfile
fips-detect seems to be built native, and can't be cross-compiled, so build it in the base image
=> build fips-detect in base

v2/pkg/config/config.go
`ose-kube-rbac-proxy:v4.11` is producing this error when interacting with data-service
I am not certain what change started causing this behavior, whether the required TLS configuration change, or a grpc update in data-service.
`ose-kube-rbac-proxy:v4.11`  is on a much older branch of the rbac-proxy
`v4.12` & `v4.13` communicate correctly
We will set the `ose-kube-rbac-proxy` statically until `v4.11` is out of service
```
2023/09/21 17:24:57 http: proxy error: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00"
2023/09/21 17:25:02 http: proxy error: write tcp 127.0.0.1:42928->127.0.0.1:8003: write: connection reset by peer
```
=> static kube-rbac-proxy tag

.github/workflows/codeql-analysis.yml, v2/pkg/prometheus/promcfg.go
For: https://github.com/redhat-marketplace/redhat-marketplace-operator/security/code-scanning/65
prior change started to unravel that none of these vars are used
prometheus pkg needs to be cleaned up overall, as half the funcs are for the removed prometheus setup, where we now use User Workload Monitoring - we just use the API funcs. That will be a separate story overall.
- remove codeql scanning for `bugfix/*, feature/*, hotfix/*` branches. This results in duplicate scan tasks for PRs, and is only useful for `release/*` branch validation.
=> fix: remove unused vars

datareporter/v2/README.md, datareporter/v2/config/manifests/bases/ibm-data-reporter-operator.clusterserviceversion.yaml, datareporter/v2/config/samples/marketplace_v1alpha1_datareporterconfig.yaml, datareporter/v2/hack/test/datareporterconfig.yaml
The namespace `openshift-redhat-marketplace` is no longer used - using `redhat-marketplace` namespace name instead.
=> Fix the namespace name to redhat-marketplace

v2/pkg/utils/k8s.go
https://pkg.go.dev/github.com/operator-framework/api@v0.18.0/pkg/operators/v1alpha1#RegistryPoll
`RawInterval` is the correct field that is interpreted for the CatalogSource
Using `Interval` resulted in an incomplete RegistryPoll, and a InvalidIntervalError Status error. The error was non-fatal, but resulted in an undesired default polling interval.
Issue reported by Piotr Godowski
=> fix: use rawinterval for registrypoll

v2/assets/metric-state/meterdefinition.yaml, v2/assets/prometheus/user-workload-monitoring-meterdefinition.yaml, v2/assets/reporter/meterdefinition.yaml, v2/pkg/config/config.go
- Change infrastructure MeterDefinitions to a 24h time period for reporting, to reduce frequent data points (requested by Mari)
- Remove KubeRbacProxy override to tagged versioned image, always use the image resolved from the utils.Makefile, with sha256 (reported bug)
=> Update infra MeterDef, fix KubeRbacProxy tag bug

datareporter/v2/main.go, datareporter/v2/pkg/datafilter/datafilter.go, datareporter/v2/pkg/datafilter/datafilter_suite_test.go, datareporter/v2/pkg/events/event_accumulator.go, datareporter/v2/pkg/events/event_processor.go, datareporter/v2/pkg/events/event_reporter.go, datareporter/v2/pkg/events/event_type.go, datareporter/v2/pkg/server/server_suite_test.go
Move the send to the eventChan from the handler to DataFilters, as a match may override its manifestType
Provide eventEngine & Config pointers to DataFilters
Change the accumulator map key from user to {user, manifestType}
Default path should function the same, TBD to test a filtered path
=> feat: dro manifestType override

datareporter/v2/pkg/datafilter/datafilter.go, datareporter/v2/pkg/datafilter/datafilter_test.go, datareporter/v2/pkg/selector/selector_test.go, datareporter/v2/pkg/server/server_suite_test.go, datareporter/v2/pkg/server/server_test.go, datareporter/v2/pkg/uploader/uploader.go
Fix the datafilter possible double transform
Fix the datafilter goroutine/channel waiting
Log instead of err for failed httpclient assertation, such that httptest will function correctly
Enable auth tests
Update test data payload
Complete the test through the server handler
Enable logger for uploader
Fix parse for token/suffix to return proper string instead of json string
=> feat: datafilter fixes and tests

datareporter/v2/main.go, datareporter/v2/pkg/logger/logger.go, datareporter/v2/pkg/uploader/uploader.go
- add logger to map retryablehttp to ctrl.Log
- add request tracing levels
modified logging levels are done via arg
```kubectl patch deployments.apps ibm-data-reporter-operator-controller-manager --type=json -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--zap-log-level=5" }]'```
- request header map should be copied not shallow
=> add debug logging

datareporter/v2/api/v1alpha1/componentconfig_types.go, datareporter/v2/config/crd/bases/marketplace.redhat.com_componentconfigs.yaml, datareporter/v2/config/crd/bases/marketplace.redhat.com_datareporterconfigs.yaml, datareporter/v2/config/manager/component_config.yaml, datareporter/v2/config/manager/kustomization.yaml, datareporter/v2/controllers/datareporterconfig_controller.go, datareporter/v2/pkg/datafilter/datafilter.go, datareporter/v2/pkg/uploader/uploader.go
- update the default handler timeout, at prev 3s timeout would occur if 
- controller reconcile took some time, locks the datafilter to update it blocking new requests
- upstream destination responds slowly
- commit updated generated bases with updated description
- Perf: Maintain a watch predicate for secrets/configmaps that refer only to objects found in the DataReporterConfig. Do not reconcile on arbitrary secrets/configmaps as each reconcilation causes datafilter lock and request delay.
- Fix datafilter lock, should be write lock
- Don't read response code on error, leads to NPE
=> fix: npe, do not access nil resp on err

README.md, v2/README.md, v2/config/rbac/role_binding.yaml, v2/config/rbac_classic/role_binding.yaml
- move the ClusterRoleBinding for manager to rbac_classic, and correctly include the additional static namespaces
- update the instructions to use the general `oc adm` command to create a new binding. updating the existing binding could be overwritten by an upgrade.
=> fix: update alt namespace rbac details

datareporter/v2/pkg/server/server.go
restore sending the event body back as part of the /v1/event POST response
even though the response is useless, changing the behavior was breaking, since some consumers are checking the response body
Prior Release:
https://github.com/redhat-marketplace/redhat-marketplace-operator/blob/2.13.5/datareporter/v2/pkg/server/server.go#L98-L99
=> fix: restore /v1/event respones body

README.md, datareporter/v2/README.md, deployer/v2/README.md, reporter/v2/pkg/reporter/uploader.go, v2/README.md, v2/controllers/marketplace/meterbase_controller.go, v2/pkg/utils/env.go
- Update code comm endpoints to new swc.saas.ibm.com domain
- Update documentation links to swc.saas.ibm.com domain
- Indicate this is for SWC & RHM customers
- Debrand from specific SWC or RHM terms where possible, favoring SWC if necessary
Checklist
TBD
- registry
=> fix: use swc domain, update doc

utils.Makefile, v2/assets/dataservice/statefulset.yaml, v2/assets/razee/remote-resource-s3.yaml, v2/assets/razee/watch-keeper.yaml, v2/assets/reporter/cronjob.yaml, v2/assets/reporter/user-workload-monitoring-job.yaml, v2/pkg/config/config.go
- images by digest should be set to imagePullPolicy: IfNotPresent
- update kube-rbac-proxy to v4.15
- fix the mismatched rrs3 deployment name not passing the digest image from env var
=> fix: proxy v4.15, rrs3 relatedImage, imagepullpolicy

metering/v2/pkg/filter/lookup.go, v2/controllers/marketplace/meterbase_controller.go, v2/main.go
- metric-state
- switch the CSV get to PartialObjectMetadata, which causes a use of the metadataclient
- The standard client full CSV Get will cause a ListWatch to start, and cache all CSVs on the cluster, which leads to high memory usage
- change the installedByNamespace func to receive a generic client Object interface, and read the metadata of the csv PartialObjectMetadata
ibm-metrics-operator
- switch the byobject field selector to namespaces scope, introduced in controller-runtime v0.16, should be a more efficient ListWatch
- scope the statefulset cache to just pod namespace and user-workload-monitoring namespace, as we check for prometheus state
- set the clusterserviceversion cache to just objects that are not copies, via labelselector, trim the Spec, we only need the metadata
- …
=> fix: reduce cache footprint of csvs

v2/go.mod
Dependabot is firing alerts for v2/go.mod, even though dgrijalva is neither in any go.mod or go.sum
https://github.com/redhat-marketplace/redhat-marketplace-operator/security/dependabot/219
=> fix: replace jwt to satisfy depbot

hack/certify/certify.sh, v2/controllers/marketplace/marketplaceconfig_controller.go
- update certify script to v4.16 catalog, follow redirects for tkn-client download
- modify unregistration when marketplaceconfig is deleted
- do not execute if in disconnected mode
- do not block on error, and retry on http call
=> fix: do not disconnected unregister, or block finalizer/deletion

airgap/v2/go.mod, airgap/v2/go.sum, airgap/v2/pkg/database/filestore.go, airgap/v2/pkg/dqlite/setup_linux.go
- `sigs.k8s.io/controller-runtime/pkg/log` not initialized, use already available fileStore Logger
- Change data-service basepath from baseDir + URL (host:port) to baseDir + Name("airgap")
- replace any invalid characters for Windows to allow Windows NFS storage host to work
- Wrap write/locking transactions with a retry for database is locked
=> win nfs compat, wTx retry

reporter/v2/pkg/reporter/uploader.go, v2/controllers/marketplace/clusterregistration_controller.go, v2/controllers/marketplace/marketplaceconfig_controller.go, v2/controllers/marketplace/marketplaceconfig_controller_test.go, v2/controllers/marketplace/meterreport_creator_controller_test.go, v2/controllers/marketplace/razeedeployment_controller_test.go, v2/controllers/marketplace/suite_test.go, v2/pkg/marketplace/marketplace_client.go, v2/pkg/marketplace/marketplace_client_test.go, v2/pkg/utils/secretutils.go
- Refactor utils SecretFetcherBuilder to parse, validate, and set token & claims. Update consumers
- uploader
- clusterregistration_controller
- marketplaceconfig_controller
- Move MarketplaceClaims to utils. Update consumers
- marketplace_client
- secretfetcher
- secretutils
- Handle decode validation, token and claims as part of SecretFetcherBuilder ReturnSecret
- Reduce token validatation for controller logic flows
- ibm-entitlement-key jwt written into secret/redhat-marketplace-pull-secret will be handled as type ibm-entitlement-key
- warn in log; reduces unexpected behavior
- Remove account checking / marketplace calls from marketplaceconfig controller
- Handle cluster & account exists status in cluster registration controller, all marketplace calls
- reduces reconciled calls to …
=> feat: refactor SecretFetcher, controller marketplace calls

airgap/v2/Dockerfile, authchecker/v2/Dockerfile, base/dataservice.Dockerfile, datareporter/v2/Dockerfile, metering/v2/Dockerfile, reporter/v2/Dockerfile, v2/Dockerfile, v2/hack/docker/bin/entrypoint
For UBI9, openssl v3, the GetSymbolPointer for `FIPS_mode` in fips-detect is no longer correct and leads to an error.
https://github.com/acardace/fips-detect/blob/main/pkg/fips/fips.go#L115
It may be that a Get for [EVP_default_properties_is_fips_enabled](https://docs.openssl.org/3.0/man3/EVP_set_default_properties/) would be a correct substitution
https://github.com/dacleyra/fips-detect/blob/main/pkg/fips/fips.go#L115
https://docs.openssl.org/3.0/man3/
In any case, at this point we have confidence we are building with openssl fips with the ubi go-toolset, so the tool is not necessary.
=> fix: remove fips-detect

v2/controllers/marketplace/clusterregistration_controller.go, v2/controllers/marketplace/deployment_controller.go, v2/main.go, v2/pkg/utils/secretutils.go
- Explicitly delete pull secret on marketplaceconfig delete, as relying on garbage collection was a race condition. This could lead to marketplaceconfig being recreated by the reconciler.
- Correct the scope of the predicate to namespace for DeploymentReconciler. Because configmap and service kinds have cluster cache scope, a configmap or service with specific names could trigger reconciliation for the wrong namespace, leading to a "unknown namespace for the cache" error.
=> fix: secret delete race, deploymentreconciler predicate

v2/controllers/marketplace/clusterregistration_controller.go
this piece of the flag logic should be outside of the !disconnected case
=> fix: rhmAccountExists always for RHMPullSecretName

reporter/v2/pkg/reporter/upload_task.go
A failed GetFile() may return a nil file, don't use the file id from the return when logging the error
=> fix: prevent NPE on GetFile err

utils.Makefile
New images moved to: https://catalog.redhat.com/software/containers/openshift4/ose-kube-rbac-proxy-rhel9/652809a5244cb343fb4a4b66
=> fix: update kube-rbac-proxy

base/dataservice.Dockerfile
Update go-toolset for base images before package updates
=> fix: go-toolset:1.22

datareporter/v2/Makefile, v2/Makefile
No specific deprecated or removed features
https://docs.openshift.com/container-platform/4.18/release_notes/ocp-4-18-release-notes.html#ocp-4-18-deprecated-removed-features_release-notes
=> feat: OpenShift 4.18 support

v2/config/rbac/reporter_cluster_role.yaml, v2/controllers/marketplace/meterbase_controller.go
- reporter reads these resources for infrastructure reporting
- switch to metric-state meterdefinition to drive infrastructure reporting, reporter job query only produces results on failures
=> fix: nodes, consoles, clusterversion rbac for reporter

.github/workflows/branch_build.yml, .github/workflows/build_base.yml, .github/workflows/license.yaml, .github/workflows/publish.yml, .github/workflows/release_status.yml, airgap/v2/go.mod, authchecker/v2/go.mod, base/dataservice.Dockerfile, cue.mod/go.mod, datareporter/v2/go.mod, datareporter/v2/hack/opm-builder.Dockerfile, metering/v2/go.mod, reporter/v2/go.mod, utils.Makefile, v2/go.mod, v2/hack/opm-builder.Dockerfile, v2/scripts/go.mod, v2/tools/connect/go.mod, v2/tools/version/go.mod
- update to go1.23
- update grpc-health-probe to v0.4.37
- Builder available: https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?image=67f7e5d0639042b2fe77b475
This is likely to fail checks as the base builder will not be updated to 1.23 until after merge
=> fix: update to go1.23

datareporter/v2/go.mod, datareporter/v2/go.sum, reporter/v2/go.mod, reporter/v2/go.sum, v2/assets/metric-state/deployment.yaml, v2/version/version.go
- update mapstructure: https://github.com/redhat-marketplace/redhat-marketplace-operator/security/dependabot/271
- remove metric-state tolerations
- this should have been removed when nodeaffinity was adjusted some time ago, it is not necessary for metric-state to prefer scheduling on master node
=> update mapstructure, remove metric-state tolerations

utils.Makefile, v2/apis/marketplace/v1alpha1/marketplaceconfig_types.go, v2/apis/marketplace/v1alpha1/meterbase_types.go, v2/controllers/marketplace/dataservice_controller.go, v2/controllers/marketplace/marketplaceconfig_controller.go, v2/pkg/manifests/factory.go, v2/pkg/utils/k8s.go, v2/pkg/utils/k8s_test.go
Chore
- reorder some items in utils.Makefile that were causing variable resolution issues
Feature
Add a StorageClassName to the MarketplaceConfig & MeterBase Spec
The linting/admission-control tool Kyverna fails on empty StatefulSet.Spec.VolumeClaimTemplates.[].StorageClassName
Despite that this can be specified via a defaultStorageClass, pre-defined PhysicalVolumeClaims, or when manually allocation PersistentVolumes.
- Provide a spec.storageClassName on MarketplaceConfig. This is an immutable field that will set the spec.volumeClaimTemplates.[].storageClass on the data-service StatefulSet, which is also immutable
- If the StatefulSet exists, the reconciler will use the existing immutable value
- If the PersistentVolumeClaims are already created, the reconciler will use its value
- If …
=> Feature: Add a StorageClassName to the MarketplaceConfig & MeterBase Spec

datareporter/v2/config/manager/manager.yaml, v2/assets/dataservice/pdb.yaml, v2/assets/dataservice/statefulset.yaml, v2/assets/reporter/cronjob.yaml, v2/controllers/marketplace/dataservice_controller.go, v2/main.go, v2/pkg/manifests/factory.go
Modifications to comply with the following policy sets
https://github.ibm.com/CloudPakOpenContent/ford-caas-audit/tree/main/policies
https://github.com/ibm-mas/kyverno-policies
- Require Read-Only Root Filesystem
- Update datareporter-operator to set readOnlyRootFilesystem: true
- Update reporter cronjob to set readOnlyRootFilesystem: true
- Restrict EmptyDir Volume Types
- Update datareporter-operator
- Mount a emptyDir tmp with a sizeLimit, where reports are temporarily written to 
- Update reporter cronjob
- Mount a emptyDir tmp with a sizeLimit, where reports are temporarily written to 
- Require PodDisruptionBudget
- data-service should retain a quorum of N/2 + 1 (default: 3 replicas, 2 minAvailable)
- Add PodDisruptionBudget CRUD to dataservice operator
- Add Watch
- Add to Create …
=> feat: updates for kyverno policies
