Makefile
cmd/manager/main.go
cmd/manager/wire_gen.go
deploy/chart/values.yaml
pkg/controller/add_node.go
pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go
pkg/controller/razeedeployment/razeedeployment_controller.go
pkg/controller/razeedeployment/razeedeployment_controller_test.go
pkg/controller/subscription/subscription_controller_test.go
pkg/utils/k8s_test.go

Issue: https://github.ibm.com/symposium/track-and-plan/issues/6222
What changed:
- Added a controller for node for checking the label [`"razee/watch-resource":"lite"`] and patching it if absent.
- Updated the roles for getting and updating node, clusterversion resources  
- Added a code snippet for patching the label to clusterversion

Feature/node controller 

---

deploy/chart/values.yaml
pkg/apis/marketplace/v1alpha1/marketplaceconfig_types.go
pkg/controller/marketplaceconfig/marketplaceconfig_controller.go
pkg/controller/marketplaceconfig/marketplaceconfig_controller_test.go
pkg/utils/env.go
pkg/utils/k8s.go

Issue: https://github.ibm.com/symposium/track-and-plan/issues/6539
To add a catalogSource for IBM products

feature/add catalog source for IBM products

---

deploy/chart/values.yaml
pkg/controller/subscription/subscription_controller.go
pkg/controller/subscription/subscription_controller_test.go

Bug found, reverting commit. This reverts commit 77046a8d455875c7211bad65a6e141cefece65e6.

Revert "Feature/uninstall subscription (#28)"

---

pkg/utils/reconcileutils/reconcile_test.go

hot fix for two broken reconcile utils tests.

marked tests in reconcileutils as pending

---

docs/meterdefinition-onboarding.md

Improving the meterdef onboarding docs

---

v2/controllers/marketplace/clusterregistration_controller.go
v2/controllers/marketplace/marketplaceconfig_controller.go
v2/controllers/marketplace/marketplaceconfig_controller_test.go
v2/pkg/inject/injectable.go
v2/pkg/marketplace/marketplace_client.go
v2/pkg/marketplace/marketplace_client_test.go

deleting the marketplace config should set cluster registration status to UNREGISTERED

Unregister when marketplace config is deleted

---

v2/config/default/manager_auth_proxy_patch.yaml

Specified cpu and memory requests and limits for proxy

added resources to proxy

---

reporter/v2/pkg/reporter/upload_task.go
reporter/v2/pkg/uploaders/marketplace.go
reporter/v2/pkg/uploaders/marketplace_test.go

Fixes:
- Marketplace upload marking report as unknown status 
* fixes https://github.ibm.com/symposium/track-and-plan/issues/21958

bugfix: marketplace upload status missing

---

v2/assets/razee/remote-resource-s3.yaml
v2/assets/razee/watch-keeper.yaml
v2/config/manager/patches/env_vars_patch.yaml
v2/pkg/config/config.go
v2/pkg/utils/env.go

use ubi base images for razee for certified images

ubi razee images

---

v2/Makefile
v2/version/version.go

Release 2.6.3

---

v2/config/manifests/bases/redhat-marketplace-operator.clusterserviceversion.yaml

Recommend enabling UWM in the Prereqs

prereq uwm in csv

---

README.md

Queries for getting pod resources
```
kubectl get pods -n openshift-redhat-marketplace -o jsonpath='{range .items[*]}{.metadata.name}{":"}{range .spec.containers[*]}{.name}{":"}{.resources}{end}{"\n"}{end}'
kubectl get pods -n openshift-user-workload-monitoring -o jsonpath='{range .items[*]}{.metadata.name}{":"}{range .spec.containers[*]}{.name}{":"}{.resources}{end}{"\n"}{end}'
```

update readme requirements

---

.github/workflows/branch_build.yml

Ticket:
https://zenhub.ibm.com/workspaces/symposium-workflow-5c49e21b79c5ae72931da0d6/issues/symposium/track-and-plan/25345

feat: enable whitesource scan

---

v2/controllers/marketplace/meterreport_creator_controller.go

Addresses meterreports not being cleaned up on uninstall: https://github.ibm.com/symposium/track-and-plan/issues/25572
What Changed:
- add owner refs to new meterreports
- meterbase will be the owning object, when meterbase is deleted the meterreport will be deleted
How to test: 
- uninstall, wide old meterreports
- run `make skaffold-dev` and wait for new reports to come up
- uninstall. You should see the meterreports get cleaned up

Add owner refs to new metterreports

---

v2/tools/connect/go.mod
v2/tools/connect/go.sum

update for 
https://github.com/redhat-marketplace/redhat-marketplace-operator/security/dependabot/80

fix: update for golang.org/x/text

---

airgap/v2/go.mod
airgap/v2/go.sum
authchecker/v2/go.mod
authchecker/v2/go.sum
deployer/v2/go.mod
deployer/v2/go.sum
deployer/v2/scripts/go.mod
deployer/v2/scripts/go.sum
metering/v2/go.mod
metering/v2/go.sum
reporter/v2/go.mod
reporter/v2/go.sum
tests/v2/go.mod
tests/v2/go.sum
v2/go.mod
v2/go.sum
v2/scripts/go.mod
v2/scripts/go.sum
v2/tools/connect/go.mod
v2/tools/connect/go.sum
v2/tools/skaffold-tdd-tool/go.mod
v2/tools/skaffold-tdd-tool/go.sum

For
https://github.com/redhat-marketplace/redhat-marketplace-operator/security/dependabot?q=is%3Aopen+golang.org%2Fx%2Fcrypto

golang.org/x/crypto@v0.6.0

---

deployer/v2/scripts/go.mod
v2/scripts/go.mod

https://github.com/redhat-marketplace/redhat-marketplace-operator/security/dependabot/123
https://github.com/redhat-marketplace/redhat-marketplace-operator/security/dependabot/124
fix indirect for the alert even though there is a replace

github.com/gogo/protobuf@v1.3.2

---

datareporter/v2/config/default/manager_auth_proxy_patch.yaml

Operator pods updated with licensing annotations

Add licensing annotations

---

datareporter/v2/Makefile
datareporter/v2/api/v1alpha1/componentconfig_types.go
datareporter/v2/main.go
utils.Makefile

For: https://github.ibm.com/symposium/track-and-plan/issues/28118#issuecomment-56144865

Defaulting the component config values

---

datareporter/v2/Makefile
datareporter/v2/config/manager/kustomization.yaml
datareporter/v2/skaffold.yaml
deployer/v2/go.mod
deployer/v2/go.sum
reporter/v2/go.mod
reporter/v2/go.sum
tests/v2/go.mod
tests/v2/go.sum
v2/go.mod
v2/go.sum

fix skaffold and cve for github.com/docker/distribution

fix skaffold

---

.github/workflows/codeql-analysis.yml
Makefile
airgap/v2/LICENSE
utils.Makefile

- update licenses tools
- add the LICENSE file proper to airgap/v2
- run a license check to gate forbidden licenses before saving licenses in the build workflow
- update codeql init v2

update license check

---

.github/workflows/branch_build.yml
.github/workflows/publish.yml
.github/workflows/release_status.yml

- remove commented out set-output lines, they broke syntax

fix: remove comments breaking syntax

---

.github/workflows/branch_build.yml
.github/workflows/build_base.yml
.github/workflows/publish.yml
deployer/v2/scripts/ci/workflows.cue
internal/ci/workflows.cue
v2/scripts/ci/workflows.cue

- update action versions to resolve deprecated save-state/set-output use
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

fix: update action versions to resolve deprecations

---

metering/v2/mocks/Client.go
v2/controllers/marketplace/clusterregistration_controller.go
v2/skaffold.yaml

For: https://github.ibm.com/symposium/track-and-plan/issues/30165

NPE in ClusterRegistration Controller

---

v2/version/version.go

- release 2.11.2 with updated golang version
CVE-2023-29406
CVE-2023-29409

fix: version 2.11.2

---

authchecker/v2/Dockerfile
base/Makefile
base/dataservice.Dockerfile
datareporter/v2/Dockerfile
deployer/v2/Dockerfile
metering/v2/Dockerfile
reporter/v2/Dockerfile
v2/Dockerfile

- use go build/install instead of make cross-compile, ubi go-toolset does not have cross-compiler libraries available

no cross-compile

---

airgap/v2/Dockerfile

fix airgap build

---

README.md
v2/config/manifests/bases/CSV_description.md
v2/config/manifests/bases/ibm-metrics-operator.clusterserviceversion.yaml

state supoorted storageclasses

---

.github/workflows/branch_build.yml
.github/workflows/build_base.yml
.github/workflows/codeql-analysis.yml
.github/workflows/create-branch.yaml.bk
.github/workflows/license.yaml
.github/workflows/publish.yml
.github/workflows/release_status.yml
.github/workflows/sync_branches.yml
deployer/v2/scripts/ci/workflows.cue
internal/ci/workflows.cue
v2/scripts/ci/workflows.cue

https://github.ibm.com/symposium/track-and-plan/issues/30344

update outdated github actions

---

datareporter/v2/config/manager/manager.yaml
datareporter/v2/main.go
deployer/v2/config/manager/manager.yaml
v2/assets/dataservice/statefulset.yaml
v2/assets/metric-state/deployment.yaml
v2/assets/reporter/cronjob.yaml
v2/assets/reporter/job.yaml
v2/config/manager/manager.yaml

For: https://github.ibm.com/symposium/track-and-plan/issues/30323

Added gomemlimit env on missing containers

---

reporter/v2/pkg/dataservice/dataservice.go
reporter/v2/pkg/reporter/report_task.go
reporter/v2/pkg/uploaders/insights.go
reporter/v2/pkg/uploaders/marketplace.go
v2/pkg/manifests/factory.go
v2/pkg/marketplace/marketplace_client.go
v2/pkg/prometheus/promcfg.go
v2/pkg/utils/signer/signer.go
v2/tools/connect/pkg/browser.go
v2/tools/connect/pkg/client.go

fixes for code scanning: https://github.com/redhat-marketplace/redhat-marketplace-operator/security/code-scanning
mostly missing err checks that could lead to NPE

fix: codeql warnings

---

.github/workflows/branch_build.yml
.github/workflows/build_base.yml
.github/workflows/create-branch.yaml.bk
.github/workflows/license.yaml
.github/workflows/publish.yml
.github/workflows/release_status.yml
airgap/v2/go.mod
authchecker/v2/go.mod
cue.mod/go.mod
datareporter/v2/go.mod
deployer/v2/go.mod
deployer/v2/scripts/go.mod
internal/ci/workflows.cue
metering/v2/go.mod
reporter/v2/go.mod
utils.Makefile
v2/go.mod
v2/scripts/go.mod
v2/tools/connect/go.mod
v2/tools/version/go.mod

- update operator build to go1.20

fix: go1.20

---

README.md
v2/config/manifests/bases/CSV_description.md
v2/config/manifests/bases/ibm-metrics-operator.clusterserviceversion.yaml

- update README with extended storage configuration
- update CSV with extended storage configuration

fix: update StorageClass doc

---

README.md
deployer/v2/config/manifests/bases/CSV_description.md
deployer/v2/config/manifests/bases/redhat-marketplace-operator.clusterserviceversion.yaml
v2/config/manifests/bases/CSV_description.md
v2/config/manifests/bases/ibm-metrics-operator.clusterserviceversion.yaml

fix: doc SubscriptionConfig

---

datareporter/v2/config/default/manager_auth_proxy_patch.yaml
v2/assets/dataservice/statefulset.yaml

#566 should have target master for patch release

updated cpu limitis for rbac proxy

---

datareporter/v2/pkg/datafilter/datafilter.go
datareporter/v2/pkg/datafilter/datafilter_suite_test.go
datareporter/v2/pkg/datafilter/datafilter_test.go
datareporter/v2/pkg/transformer/transformer_suite_test.go
datareporter/v2/pkg/transformer/transformer_test.go
datareporter/v2/pkg/uploader/uploader.go

- getConfigMapData to check if key in map
- enable df transformer tests
- add transform in/out payload test
- wire client to uploader

feat: update transformer tests

---

airgap/v2/go.mod
airgap/v2/go.sum
v2/go.mod
v2/go.sum

For: https://github.com/redhat-marketplace/redhat-marketplace-operator/security/dependabot/218

fix update github.com/openshift/cluster-monitoring-operator

---

v2/assets/dataservice/statefulset.yaml
v2/assets/metric-state/deployment.yaml
v2/assets/razee/remote-resource-s3.yaml
v2/assets/razee/rr-controller-deployment.yaml
v2/assets/razee/watch-keeper-deployment.yaml

component updates increased authcheck memory usage enough to start having issues with authcheck restarting, increase the max

fix: increase authcheck memory limit

---

README.md
v2/README.md

- remove/update deployment refs in readme

feat: readme remove deployment

---

base/data-service-ubi-minimal.Dockerfile
datareporter/v2/hack/opm-builder.Dockerfile
v2/hack/opm-builder.Dockerfile

generalize epel cleanup
update opm

fix: epel, opm

---

hack/must-gather.sh

Pair with wiki entry: https://github.com/redhat-marketplace/redhat-marketplace-operator/wiki/Troubleshooting-Must-Gather

chore: add must-gather bash script

---

hack/certify/certify.sh

chore: update index, use latest pipelines tag

---

v2/assets/dataservice/statefulset.yaml

- increase the timeout paramters of the grpc-health-probe for data-service

fix: increase liveness timeout

---

v2/controllers/marketplace/meterbase_controller.go

For: https://github.ibm.com/symposium/track-and-plan/issues/33605
Since we are now populating infrastructure reports with data
1. Only send 1 report.
- remove UserWorkloadMonitoringMeterDefinition, MetricStateMeterDefinition
- keep ReporterMeterDefinition
2. Only enable ReporterMeterDefinition if Account Exists

feat: do not enable infrastructure reports without an account

---

v2/controllers/marketplace/clusterregistration_controller.go
v2/pkg/marketplace/marketplace_client.go
v2/pkg/marketplace/marketplace_client_test.go

fix: remove registration check

---

v2/pkg/marketplace/marketplace_client.go

accounts api may return 2xx and not solely 200

fix: accept 2xx in marketplaceclient

---

airgap/v2/go.mod
authchecker/v2/go.mod
base/dataservice.Dockerfile
cue.mod/go.mod
datareporter/v2/go.mod
metering/v2/go.mod
reporter/v2/go.mod
v2/go.mod
v2/scripts/go.mod
v2/tools/connect/go.mod
v2/tools/version/go.mod

- update go-toolset to go1.24.6
- set toolchain to go1.24.6

update to go 1.24.6
